
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saurabh Shubham
 */
public class user_token_gen extends javax.swing.JFrame {

    /**
     * Creates new form user_token_gen
     * 
     */
    public int pass;
    public String v_no2;
    public String v_no3;
    public String v_no1;
    public String des1;
    public String des2;
    public String des3;
    public int num;
    public user_token_gen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        host = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        info1 = new javax.swing.JLabel();
        info2 = new javax.swing.JLabel();
        info3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        infon1 = new javax.swing.JLabel();
        infon2 = new javax.swing.JLabel();
        infon3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        infod1 = new javax.swing.JLabel();
        infod2 = new javax.swing.JLabel();
        infod3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Special Lane Portal Consumer part");

        jButton1.setText("Search For Vehicles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("GO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("GO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        id.setText("1");

        jButton5.setText("Log out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel5.setText("User ID");

        jLabel2.setText("User Id");

        jLabel3.setText("Driver Name");

        jLabel4.setText("Destination");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(23, 23, 23)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(0, 50, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(info2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(info1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(371, 371, 371)
                        .addComponent(infod1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jButton3))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infon1)
                                    .addComponent(infon2)
                                    .addComponent(infon3))
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infod2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infod3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(145, 145, 145))))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id)
                            .addComponent(jLabel5)))
                    .addComponent(jButton5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(host, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(infod1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(infod2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(info2)
                                .addComponent(infon2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infod3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(info3)
                                    .addComponent(infon3))
                                .addGap(8, 8, 8))
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(info1)
                        .addComponent(infon1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        setSize(new java.awt.Dimension(624, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Random rand=new Random();
        int n = rand.nextInt(1)+2;
        try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/bh";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
            String sql = "select * from owner where id = 8;" ;
            ResultSet rs = stmt.executeQuery(sql);
            //System.out.println(""+rs.next());
            if(rs.next())
            {
                String s,user,d;
                s = rs.getString("id");
                user=rs.getString("name");
                info1.setText(s);
                infon1.setText(user);
                v_no1=rs.getString("car_no");
                des1=rs.getString("dest");
                infod1.setText(des1);
            }
            else
            JOptionPane.showMessageDialog(null,"Novehicle found.","",JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e)
        {
            System.out.println("Not Connected, Error:  "+e.getMessage());
        }
        try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/bh";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
            String sql = "select * from owner where id = 3;" ;
            ResultSet rs = stmt.executeQuery(sql);
            //System.out.println(""+rs.next());
            if(rs.next())
            {
                String s,user;
                s = rs.getString("id");
                user=rs.getString("name");
                info2.setText(s);
                infon2.setText(user);
                v_no2=rs.getString("car_no");
                des2=rs.getString("dest");
                infod2.setText(des2);
            }
            else
            JOptionPane.showMessageDialog(null,"Novehicle found.","",JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e)
        {
            System.out.println("Not Connected, Error:  "+e.getMessage());
        }
        try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/bh";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
            String sql = "select * from owner where id = 5;" ;
            ResultSet rs = stmt.executeQuery(sql);
            //System.out.println(""+rs.next());
            if(rs.next())
            {
                String s,user;
                s = rs.getString("id");
                user=rs.getString("name");
                info3.setText(s);
                infon3.setText(user);
                v_no3=rs.getString("car_no");
                des3=rs.getString("dest");
                infod3.setText(des3);
            }
            else
            JOptionPane.showMessageDialog(null,"Novehicle found.","",JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e)
        {
            System.out.println("Not Connected, Error:  "+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String si=info1.getText();
        pass=Integer.parseInt(si);
        driver_info u = new driver_info();
        dispose();
        u.v.setText(""+pass);
        u.name.setText(""+infon1.getText());
        u.vno.setText(""+v_no1);
        u.setVisible(true);
        u.desti.setText(""+des1);
        Random rand=new Random();
        num = rand.nextInt(9000)+1000;
        u.tnum.setText(""+num);
        try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/bh";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
            String sql = "select * from owner where id = 8;" ;
            ResultSet rs = stmt.executeQuery(sql);
            ResultSet r;
            String sq="";
            //System.out.println(""+rs.next());
            if(rs.next())
            {
                String s;
                s=rs.getString("x");
                if(s.equals(""+0))
                sq="update owner set x='" +num+ "'where id=8";
                else{
                    s=rs.getString("y");
                    if(s.equals(""+0))
                    sq="update owner set y='" +num+ "'where id=8";
                    else{
                        s=rs.getString("z");
                        if(s.equals(""+0))
                        sq="update owner set z='" +num+ "'where id=8";
                        else{
                            s=rs.getString("w");
                            if(s.equals(""+0))
                            sq="update owner set w='" +num+ "'where id=8";
                            else{
                                u.v.setText("");u.name.setText("");u.vno.setText("");u.desti.setText("");
                                u.tnum.setText("");
                                JOptionPane.showMessageDialog(null,"vehicle is full.","",JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    }
                }
                stmt.executeUpdate(sq);

            }
            else
            JOptionPane.showMessageDialog(null,"No vehicle found.","",JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e)
        {
            System.out.println("Not Connected, Error:  "+e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String si=info2.getText();
        pass=Integer.parseInt(si);
        driver_info u = new driver_info();
        dispose();
        u.v.setText(""+pass);
        u.name.setText(""+infon2.getText());
        u.vno.setText(""+v_no1);
        u.setVisible(true);
        u.desti.setText(""+des1);
        Random rand=new Random();
        num = rand.nextInt(9000)+1000;
        u.tnum.setText(""+num);
        try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/bh";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
            String sql = "select * from owner where id = 3;" ;
            ResultSet rs = stmt.executeQuery(sql);
            ResultSet r;
            String sq="";
            //System.out.println(""+rs.next());
            if(rs.next())
            {
                String s;
                s=rs.getString("x");
                if(s.equals(""+0))
                sq="update owner set x='" +num+ "'where id=3";
                else{
                    s=rs.getString("y");
                    if(s.equals(""+0))
                    sq="update owner set y='" +num+ "'where id=3";
                    else{
                        s=rs.getString("z");
                        if(s.equals(""+0))
                        sq="update owner set z='" +num+ "'where id=3";
                        else{
                            s=rs.getString("w");
                            if(s.equals(""+0))
                            sq="update owner set w='" +num+ "'where id=3";
                            else{
                                u.v.setText("");u.name.setText("");u.vno.setText("");u.desti.setText("");
                                u.tnum.setText("");
                                JOptionPane.showMessageDialog(null,"vehicle is full.","",JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    }
                }
                stmt.executeUpdate(sq);

            }
            else
            JOptionPane.showMessageDialog(null,"No vehicle found.","",JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e)
        {
            System.out.println("Not Connected, Error:  "+e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String si=info3.getText();
        pass=Integer.parseInt(si);
        driver_info u = new driver_info();
        dispose();
        u.v.setText(""+pass);
        u.name.setText(""+infon3.getText());
        u.vno.setText(""+v_no1);
        u.setVisible(true);
        u.desti.setText(""+des1);
        Random rand=new Random();
        num = rand.nextInt(9000)+1000;
        u.tnum.setText(""+num);
        try{
            Class.forName("java.sql.Driver");
            String database = "jdbc:mysql://localhost:3306/bh";
            Connection conn = DriverManager.getConnection(database, "root","");
            Statement stmt = conn.createStatement();
            String sql = "select * from owner where id = 5;" ;
            ResultSet rs = stmt.executeQuery(sql);
            ResultSet r;
            String sq="";
            //System.out.println(""+rs.next());
            if(rs.next())
            {
                String s;
                s=rs.getString("x");
                if(s.equals(""+0))
                sq="update owner set x='" +num+ "'where id=5";
                else{
                    s=rs.getString("y");
                    if(s.equals(""+0))
                    sq="update owner set y='" +num+ "'where id=5";
                    else{
                        s=rs.getString("z");
                        if(s.equals(""+0))
                        sq="update owner set z='" +num+ "'where id=5";
                        else{
                            s=rs.getString("w");
                            if(s.equals(""+0))
                            sq="update owner set w='" +num+ "'where id=5";
                            else{
                                u.v.setText("");u.name.setText("");u.vno.setText("");u.desti.setText("");
                                u.tnum.setText("");
                                JOptionPane.showMessageDialog(null,"vehicle is full.","",JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    }
                }
                stmt.executeUpdate(sq);

            }
            else
            JOptionPane.showMessageDialog(null,"No vehicle found.","",JOptionPane.ERROR_MESSAGE);

        }
        catch(Exception e)
        {
            System.out.println("Not Connected, Error:  "+e.getMessage());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
login l = new login();
      dispose();
      l.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
selector s = new selector();
s.id.setText(this.id.getText());
dispose();
s.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_token_gen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_token_gen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_token_gen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_token_gen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_token_gen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel host;
    public static javax.swing.JLabel id;
    private javax.swing.JLabel info1;
    private javax.swing.JLabel info2;
    private javax.swing.JLabel info3;
    public static javax.swing.JLabel infod1;
    public static javax.swing.JLabel infod2;
    public static javax.swing.JLabel infod3;
    private javax.swing.JLabel infon1;
    private javax.swing.JLabel infon2;
    private javax.swing.JLabel infon3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
